import { type ServiceType } from './services'

export interface Facility {
  id: string
  name: string
  address: string
  district: string
  lat: number
  lng: number
  type: 'Hospital' | 'BHC' | 'Clinic'
  services: ServiceType[]
  unverified?: boolean
  communityFlagged?: boolean
  _sources?: Record<string, string>
  tags: string[]
  // Filter fields
  isBHC: boolean
  isPhilHealthKonsulta: boolean
  isPhilHealthAccredited: boolean
  acceptsWalkIn: boolean
  acceptsReferral: boolean
  hasEmergency: boolean
  inpatient: boolean
  outpatient: boolean
  hasLaboratory: boolean
  hasDiagnostics: boolean
  hasMalasakitCenter: boolean
  hasSeniorLane: boolean
  hours: string
  is24Hours: boolean
  typicalWaitLevel: 'low' | 'medium' | 'high'
}

export const FACILITIES: Facility[] = [
  // ═══════════════ DOH-RETAINED HOSPITALS ═══════════════
  // Source: slh.doh.gov.ph, DOH records
  { id:'h1', name:'San Lazaro Hospital', address:'Quiricada St, Sta. Cruz, Manila', district:'District III', lat:14.6139, lng:120.9806, type:'Hospital', services: ['Infectious Disease', 'Internal Medicine', 'Pediatrics', 'OB-GYN', 'Surgery', 'ENT', 'Ophthalmology', 'Dermatology', 'Dental / Oral Health', 'Psychiatry', 'Chest X-Ray (CXR)', 'Abdominal Ultrasound', 'Complete Blood Count (CBC)', 'ECG/EKG'], _sources: {"services": "https://slh.doh.gov.ph", "philhealthAccredited": "https://www.philhealth.gov.ph/partners/providers/institutional/map/", "lastVerified": "2026-04-25"}, tags:['DOH','Specialist','24/7'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:true, acceptsReferral:true, hasEmergency:true, inpatient:true, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:true, hasSeniorLane:true, hours:'24/7', is24Hours:true, typicalWaitLevel:'high' },
  // Source: DOH records, mariahealth.ph
  { id:'h2', name:'Dr. Jose Fabella Memorial Hospital', address:'Lope de Vega St, Sta. Cruz, Manila', district:'District III', lat:14.6060, lng:120.9830, type:'Hospital', services: ['OB-GYN', 'Neonatal ICU (NICU)', 'Family Medicine', 'Abdominal Ultrasound', 'Complete Blood Count (CBC)', 'Chest X-Ray (CXR)'], _sources: {"services": "https://fabella.doh.gov.ph", "philhealthAccredited": "https://www.philhealth.gov.ph/partners/providers/institutional/map/", "lastVerified": "2026-04-25"}, tags:['DOH','Maternity','Specialist'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:true, acceptsReferral:true, hasEmergency:true, inpatient:true, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:true, hasSeniorLane:true, hours:'24/7', is24Hours:true, typicalWaitLevel:'high' },
  // Source: jrrmmc.gov.ph — 18 verified clinical departments
  { id:'h3', name:'Jose R. Reyes Memorial Medical Center', address:'Rizal Ave, Sta. Cruz, Manila', district:'District III', lat:14.6110, lng:120.9820, type:'Hospital', services: ['General Medicine', 'Surgery', 'Orthopedics', 'Pediatrics', 'OB-GYN', 'Cardiology', 'Dermatology', 'ENT', 'Neurology', 'Ophthalmology', 'Urology', 'Dental / Oral Health', 'Psychiatry', 'Rehabilitation Medicine', 'Radiation Therapy', 'Nuclear Medicine', 'ECG/EKG', 'Chest X-Ray (CXR)', 'MRI', 'CT Scan', 'Abdominal Ultrasound', 'Complete Blood Count (CBC)', '2D Echo'], _sources: {"services": "https://jrrmmc.gov.ph", "philhealthAccredited": "https://www.philhealth.gov.ph/partners/providers/institutional/map/", "lastVerified": "2026-04-25"}, tags:['DOH','Tertiary','Level III'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:true, acceptsReferral:true, hasEmergency:true, inpatient:true, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:true, hasSeniorLane:true, hours:'24/7', is24Hours:true, typicalWaitLevel:'high' },
  // Source: pgh.gov.ph — 19 verified clinical departments
  { id:'h4', name:'Philippine General Hospital', address:'Taft Ave, Ermita, Manila', district:'District V', lat:14.5785, lng:120.9847, type:'Hospital', services: ['Internal Medicine', 'Surgery', 'Pediatrics', 'OB-GYN', 'Neurology', 'Neurosurgery', 'Orthopedics', 'Cardiology', 'Pulmonology', 'Nephrology', 'Oncology', 'Dermatology', 'Ophthalmology', 'ENT', 'Psychiatry', 'Rehabilitation Medicine', 'Dental / Oral Health', 'Emergency Room (ER)', 'Trauma Care', 'Intensive Care Unit (ICU)', 'Neonatal ICU (NICU)', 'Wound Debridement / Dressing', 'Poison Control', 'Dialysis (Hemodialysis)', 'Chemotherapy', 'Radiation Therapy', 'Blood Transfusion', 'Physical Therapy', 'CT Scan', 'MRI', 'Chest X-Ray (CXR)', 'Abdominal Ultrasound', 'Complete Blood Count (CBC)', 'ECG/EKG', '2D Echo'], _sources: {"services": "https://pgh.gov.ph/services", "philhealthAccredited": "https://www.philhealth.gov.ph/partners/providers/institutional/map/", "lastVerified": "2026-04-25"}, tags:['DOH','UP','Tertiary','Level III','Teaching'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:false, acceptsReferral:true, hasEmergency:true, inpatient:true, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:true, hasSeniorLane:true, hours:'24/7', is24Hours:true, typicalWaitLevel:'high' },

  // ═══════════════ DOH-RETAINED / CITY-RUN HOSPITALS ═══════════════
  // Source: DOH records, mariahealth.ph — TMC is DOH-retained (NOT city-run)
  { id:'h5', name:'Tondo Medical Center', address:'Honorio Lopez Blvd, Tondo, Manila', district:'District II', lat:14.6300, lng:120.9669, type:'Hospital', services: ['General Medicine', 'Surgery', 'Pediatrics', 'OB-GYN', 'Internal Medicine', 'ENT', 'Ophthalmology', 'Dental / Oral Health', 'Psychiatry', 'Chest X-Ray (CXR)', 'Abdominal Ultrasound', 'ECG/EKG', 'Complete Blood Count (CBC)', 'Urinalysis'], _sources: {"services": "https://tmc.doh.gov.ph", "philhealthAccredited": "https://www.philhealth.gov.ph/partners/providers/institutional/map/", "lastVerified": "2026-04-25"}, tags:['DOH','Tertiary','Level III'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:true, acceptsReferral:true, hasEmergency:true, inpatient:true, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:true, hasSeniorLane:true, hours:'24/7', is24Hours:true, typicalWaitLevel:'medium' },
  // Source: manila.gov.ph, mariahealth.ph — City-run Level III
  { id:'h6', name:'Ospital ng Maynila Medical Center', address:'Roxas Blvd, Malate, Manila', district:'District V', lat:14.5700, lng:120.9830, type:'Hospital', services: ['General Medicine', 'Surgery', 'Pediatrics', 'OB-GYN', 'Cardiology', 'Orthopedics', 'ENT', 'Ophthalmology', 'Dental / Oral Health', 'Family Medicine', 'Dialysis (Hemodialysis)', 'Chest X-Ray (CXR)', 'Abdominal Ultrasound', 'CT Scan', 'MRI', 'ECG/EKG', 'Complete Blood Count (CBC)', '2D Echo', 'Physical Therapy'], tags:['City-run','Level III','PhilHealth'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:true, acceptsReferral:true, hasEmergency:true, inpatient:true, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:true, hasSeniorLane:true, hours:'24/7', is24Hours:true, typicalWaitLevel:'medium' },
  // Source: healthspace.ph, hellodoctor.com.ph — City-run Level I (NOT DOH)
  { id:'h7', name:'Gat Andres Bonifacio Memorial Medical Center', address:'Delpan St, Tondo, Manila', district:'District I', lat:14.6350, lng:120.9620, type:'Hospital', services: ['General Medicine', 'Surgery', 'Pediatrics', 'OB-GYN', 'Internal Medicine', 'Family Medicine', 'Dermatology', 'ENT', 'Ophthalmology', 'Dental / Oral Health', 'Dialysis (Hemodialysis)', 'Emergency Room (ER)', 'Chest X-Ray (CXR)', 'ECG/EKG', 'Complete Blood Count (CBC)'], tags:['City-run','Level I','PhilHealth'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:true, acceptsReferral:true, hasEmergency:true, inpatient:true, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:true, hasSeniorLane:true, hours:'24/7', is24Hours:true, typicalWaitLevel:'medium' },
  // Source: mariahealth.ph, healthspace.ph — City-run
  { id:'h8', name:'Sta. Ana Hospital', address:'New Panaderos St, Sta. Ana, Manila', district:'District VI', lat:14.5820, lng:121.0060, type:'Hospital', services: ['General Medicine', 'Pediatrics', 'OB-GYN', 'Surgery', 'Dental / Oral Health', 'Chest X-Ray (CXR)', 'ECG/EKG', 'Complete Blood Count (CBC)', 'Abdominal Ultrasound'], tags:['City-run','Level II','PhilHealth'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:true, acceptsReferral:true, hasEmergency:true, inpatient:true, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:false, hasSeniorLane:true, hours:'24/7', is24Hours:true, typicalWaitLevel:'medium' },
  { id:'h9', name:'Jose Abad Santos General Hospital', address:'C-3 Rd, Tondo, Manila', district:'District I', lat:14.6250, lng:120.9700, type:'Hospital', services: ['General Medicine', 'Emergency Room (ER)', 'Pediatrics', 'OB-GYN', 'Complete Blood Count (CBC)', 'Chest X-Ray (CXR)'], tags:['City-run','Level II'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:true, acceptsReferral:true, hasEmergency:true, inpatient:true, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:false, hasSeniorLane:true, hours:'24/7', is24Hours:true, typicalWaitLevel:'low' },
  { id:'h10', name:'Ospital ng Sampaloc', address:'Espana Blvd, Sampaloc, Manila', district:'District IV', lat:14.6100, lng:120.9900, type:'Hospital', services: ['General Medicine', 'Pediatrics', 'OB-GYN', 'Complete Blood Count (CBC)', 'Chest X-Ray (CXR)', 'Abdominal Ultrasound'], tags:['City-run','Level I'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:true, acceptsReferral:true, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:false, hasSeniorLane:true, hours:'7:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low' },

  // ═══════════════ PRIVATE HOSPITALS ═══════════════
  // Source: maniladoctors.com.ph — Tertiary Level III, Platinum ACI Accredited
  { id:'h11', name:'Manila Doctors Hospital', address:'667 United Nations Ave, Ermita, Manila', district:'District V', lat:14.5800, lng:120.9840, type:'Hospital', services: ['General Medicine', 'Cardiology', 'Oncology', 'Surgery', 'Neurology', 'Dermatology', 'Ophthalmology', 'Psychiatry', 'Rehabilitation Medicine', 'Nuclear Medicine', 'Radiation Therapy', 'ECG/EKG', 'MRI', 'CT Scan', 'Chest X-Ray (CXR)', 'Abdominal Ultrasound', 'Complete Blood Count (CBC)', '2D Echo', 'Dialysis (Hemodialysis)'], tags:['Private','Tertiary','Level III'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:false, acceptsReferral:true, hasEmergency:true, inpatient:true, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:false, hasSeniorLane:true, hours:'24/7', is24Hours:true, typicalWaitLevel:'low' },
  // Source: cghmc.com.ph — Heart/Cancer Institutes, Robotic Surgery, PET-CT
  { id:'h12', name:'Chinese General Hospital', address:'286 Blumentritt St, Sta. Cruz, Manila', district:'District III', lat:14.6200, lng:120.9850, type:'Hospital', services: ['General Medicine', 'Surgery', 'Cardiology', 'Oncology', 'Neurology', 'Neurosurgery', 'Pediatrics', 'OB-GYN', 'Orthopedics', 'ENT', 'Ophthalmology', 'Dermatology', 'Urology', 'Rehabilitation Medicine', 'Nuclear Medicine', 'Dialysis (Hemodialysis)', 'ECG/EKG', 'Chest X-Ray (CXR)', 'Abdominal Ultrasound', 'CT Scan', 'MRI', 'Complete Blood Count (CBC)', '2D Echo'], tags:['Private','Tertiary','Level III'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:false, acceptsReferral:true, hasEmergency:true, inpatient:true, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:false, hasSeniorLane:true, hours:'24/7', is24Hours:true, typicalWaitLevel:'low' },
  // Source: usthospital.com.ph — Cancer Institute, Neuroscience, Eye, Kidney Centers
  { id:'h13', name:'University of Santo Tomas Hospital', address:'Espana Blvd, Sampaloc, Manila', district:'District IV', lat:14.6110, lng:120.9890, type:'Hospital', services: ['General Medicine', 'Surgery', 'Cardiology', 'Oncology', 'Neurology', 'Neurosurgery', 'Pediatrics', 'OB-GYN', 'Orthopedics', 'ENT', 'Ophthalmology', 'Dermatology', 'Psychiatry', 'Family Medicine', 'Rehabilitation Medicine', 'Nuclear Medicine', 'Dialysis (Hemodialysis)', 'ECG/EKG', 'MRI', 'CT Scan', 'Chest X-Ray (CXR)', 'Abdominal Ultrasound', 'Complete Blood Count (CBC)', '2D Echo', 'Physical Therapy'], tags:['Private','Tertiary','Level III','Teaching'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:false, acceptsReferral:true, hasEmergency:true, inpatient:true, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:false, hasSeniorLane:true, hours:'24/7', is24Hours:true, typicalWaitLevel:'medium' },
  { id:'h14', name:'Metropolitan Medical Center', address:'1357 G. Masangkay St, Sta. Cruz, Manila', district:'District III', lat:14.6050, lng:120.9790, type:'Hospital', services: ['General Medicine', 'Surgery', 'Cardiology', 'OB-GYN', 'Pediatrics', 'ECG/EKG', 'Chest X-Ray (CXR)', 'Complete Blood Count (CBC)', 'Abdominal Ultrasound'], tags:['Private','Tertiary'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:false, acceptsReferral:true, hasEmergency:true, inpatient:true, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:false, hasSeniorLane:true, hours:'24/7', is24Hours:true, typicalWaitLevel:'low' },
  { id:'h15', name:'Mary Johnston Hospital', address:'Norzagaray St, Tondo, Manila', district:'District II', lat:14.6180, lng:120.9730, type:'Hospital', services: ['General Medicine', 'Surgery', 'Pediatrics', 'OB-GYN', 'Chest X-Ray (CXR)', 'Complete Blood Count (CBC)'], tags:['Private','Level II'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:true, acceptsReferral:true, hasEmergency:true, inpatient:true, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:false, hasSeniorLane:false, hours:'24/7', is24Hours:true, typicalWaitLevel:'medium' },
  { id:'h16', name:'Manila Central University – FDT Medical Foundation', address:'EDSA, Caloocan (near Manila border)', district:'District IV', lat:14.6280, lng:120.9880, type:'Hospital', services: ['General Medicine', 'Pediatrics', 'OB-GYN', 'Dental / Oral Health', 'Complete Blood Count (CBC)', 'Chest X-Ray (CXR)'], tags:['Private','Teaching'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:true, acceptsReferral:true, hasEmergency:false, inpatient:true, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:false, hasSeniorLane:false, hours:'7:00 AM - 8:00 PM', is24Hours:false, typicalWaitLevel:'low' },

  // ═══════════════ DIAGNOSTIC / SPECIALTY CLINICS ═══════════════
  { id:'c1', name:'Hi-Precision Diagnostics – UN Ave', address:'United Nations Ave, Ermita, Manila', district:'District V', lat:14.5790, lng:120.9830, type:'Clinic', services: ['Complete Blood Count (CBC)', 'Urinalysis', 'Lipid Profile', 'HbA1c', 'Thyroid Panel', 'Liver Function Test', 'Fecalysis', 'Drug Test', 'Chest X-Ray (CXR)', 'Abdominal Ultrasound', 'ECG/EKG', '2D Echo'], tags:['Private','Diagnostic'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:false, hasSeniorLane:false, hours:'6:00 AM - 6:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'c2', name:'Healthway QualiMed – Manila', address:'Pedro Gil St, Paco, Manila', district:'District V', lat:14.5830, lng:120.9860, type:'Clinic', services: ['General Medicine', 'Complete Blood Count (CBC)', 'Urinalysis', 'ECG/EKG', 'Chest X-Ray (CXR)'], tags:['Private','Clinic','Walk-in'], isBHC:false, isPhilHealthKonsulta:false, isPhilHealthAccredited:true, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:true, hasDiagnostics:true, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'c3', name:'PhilHealth Konsulta Center – Quiapo', address:'Quezon Blvd, Quiapo, Manila', district:'District III', lat:14.5990, lng:120.9840, type:'Clinic', services: ['General Medicine', 'Complete Blood Count (CBC)', 'Urinalysis', 'Vaccination / Immunization'], tags:['PhilHealth','Konsulta','Free'], isBHC:false, isPhilHealthKonsulta:true, isPhilHealthAccredited:true, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:true, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'medium', unverified: true },

  // ═══════════════ BARANGAY HEALTH CENTERS — DISTRICT I ═══════════════
  { id:'b1', name:'Tondo Foreshore Health Center', address:'R-10 Rd, Tondo, Manila', district:'District I', lat:14.6150, lng:120.9630, type:'BHC', services: ['General Medicine', 'OB-GYN', 'Vaccination / Immunization', 'Complete Blood Count (CBC)'], tags:['BHC','Free','Konsulta'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:true, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'medium', unverified: true },
  { id:'b2', name:'Vitas Health Center', address:'Vitas, Tondo, Manila', district:'District I', lat:14.6220, lng:120.9590, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'Complete Blood Count (CBC)'], tags:['BHC','Free','Pharmacy'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b3', name:'Parola Health Center', address:'Parola Compound, Tondo, Manila', district:'District I', lat:14.6100, lng:120.9600, type:'BHC', services: ['General Medicine', 'OB-GYN', 'Vaccination / Immunization', 'TB-DOTS Treatment'], tags:['BHC','Free','TB-DOTS'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b4', name:'Dagat-Dagatan Health Center', address:'Dagat-Dagatan, Navotas border, Manila', district:'District I', lat:14.6370, lng:120.9610, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'OB-GYN'], tags:['BHC','Free','Konsulta'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },

  // ═══════════════ BARANGAY HEALTH CENTERS — DISTRICT II ═══════════════
  { id:'b5', name:'Balut Health Center', address:'Balut, Tondo, Manila', district:'District II', lat:14.6280, lng:120.9640, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'TB-DOTS Treatment', 'OB-GYN'], tags:['BHC','Free','TB-DOTS'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b6', name:'Tondo II Health Center', address:'Moriones St, Tondo, Manila', district:'District II', lat:14.6240, lng:120.9680, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'Dental / Oral Health', 'Complete Blood Count (CBC)'], tags:['BHC','Free','Dental'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:true, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b7', name:'Isla de Balut Health Center', address:'Isla de Balut, Tondo, Manila', district:'District II', lat:14.6310, lng:120.9610, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'OB-GYN'], tags:['BHC','Free','Konsulta'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },

  // ═══════════════ BARANGAY HEALTH CENTERS — DISTRICT III ═══════════════
  { id:'b8', name:'San Nicolas Health Center', address:'San Nicolas, Binondo, Manila', district:'District III', lat:14.6010, lng:120.9770, type:'BHC', services: ['General Medicine', 'TB-DOTS Treatment', 'Dental / Oral Health', 'Complete Blood Count (CBC)'], tags:['BHC','Free','TB-DOTS','Dental'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:true, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b9', name:'Binondo Health Center', address:'Ongpin St, Binondo, Manila', district:'District III', lat:14.6000, lng:120.9730, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'OB-GYN'], tags:['BHC','Free','Konsulta'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b10', name:'Sta. Cruz Health Center', address:'Rizal Ave, Sta. Cruz, Manila', district:'District III', lat:14.6130, lng:120.9810, type:'BHC', services: ['General Medicine', 'TB-DOTS Treatment', 'Vaccination / Immunization', 'OB-GYN', 'Complete Blood Count (CBC)'], tags:['BHC','Free','TB-DOTS'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:true, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'medium', unverified: true },
  { id:'b11', name:'Quiapo Health Center', address:'Quezon Blvd, Quiapo, Manila', district:'District III', lat:14.5980, lng:120.9820, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'Dental / Oral Health'], tags:['BHC','Free','Dental'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'medium', unverified: true },

  // ═══════════════ BARANGAY HEALTH CENTERS — DISTRICT IV ═══════════════
  { id:'b12', name:'Sampaloc Health Center', address:'Espana Blvd, Sampaloc, Manila', district:'District IV', lat:14.6120, lng:120.9920, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'OB-GYN', 'TB-DOTS Treatment'], tags:['BHC','Free','TB-DOTS'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:true, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b13', name:'San Miguel Health Center', address:'San Miguel, Manila', district:'District IV', lat:14.5940, lng:120.9900, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'OB-GYN'], tags:['BHC','Free','Konsulta'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b14', name:'Laging Handa Health Center', address:'Laging Handa, Sampaloc, Manila', district:'District IV', lat:14.6150, lng:120.9950, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'TB-DOTS Treatment', 'Dental / Oral Health'], tags:['BHC','Free','TB-DOTS','Dental'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },

  // ═══════════════ BARANGAY HEALTH CENTERS — DISTRICT V ═══════════════
  { id:'b15', name:'Intramuros Health Center', address:'Cabildo St, Intramuros, Manila', district:'District V', lat:14.5888, lng:120.9760, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'Complete Blood Count (CBC)'], tags:['BHC','Free','Konsulta'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:true, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b16', name:'Ermita Health Center', address:'J. Bocobo St, Ermita, Manila', district:'District V', lat:14.5810, lng:120.9810, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'OB-GYN', 'TB-DOTS Treatment'], tags:['BHC','Free','TB-DOTS'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b17', name:'Malate Health Center', address:'Remedios St, Malate, Manila', district:'District V', lat:14.5720, lng:120.9860, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'OB-GYN', 'Complete Blood Count (CBC)'], tags:['BHC','Free','Konsulta'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b18', name:'Paco Health Center', address:'Pedro Gil St, Paco, Manila', district:'District V', lat:14.5850, lng:120.9870, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'TB-DOTS Treatment', 'Dental / Oral Health'], tags:['BHC','Free','TB-DOTS','Dental'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:true, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b19', name:'Port Area Health Center', address:'Port Area, Manila', district:'District V', lat:14.5860, lng:120.9690, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'Complete Blood Count (CBC)'], tags:['BHC','Free','Konsulta'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },

  // ═══════════════ BARANGAY HEALTH CENTERS — DISTRICT VI ═══════════════
  { id:'b20', name:'Sta. Ana Health Center', address:'Sta. Ana, Manila', district:'District VI', lat:14.5790, lng:121.0040, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'OB-GYN', 'TB-DOTS Treatment'], tags:['BHC','Free','TB-DOTS'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:true, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b21', name:'Pandacan Health Center', address:'Pandacan, Manila', district:'District VI', lat:14.5870, lng:121.0000, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'Dental / Oral Health', 'OB-GYN'], tags:['BHC','Free','Dental'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b22', name:'San Andres Health Center', address:'San Andres, Manila', district:'District VI', lat:14.5740, lng:121.0010, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'Complete Blood Count (CBC)'], tags:['BHC','Free','Konsulta'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },

  // ═══════════════ ADDITIONAL CITY HEALTH OFFICES ═══════════════
  { id:'b23', name:'Manila City Health Office – Main', address:'Arroceros St, Ermita, Manila', district:'District V', lat:14.5920, lng:120.9790, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'TB-DOTS Treatment', 'OB-GYN', 'Complete Blood Count (CBC)', 'Dental / Oral Health'], tags:['City','Free','Main Office'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:true, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:true, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'medium', unverified: true },
  { id:'b24', name:'Baseco Health Center', address:'Baseco Compound, Port Area, Manila', district:'District V', lat:14.5820, lng:120.9640, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'OB-GYN', 'TB-DOTS Treatment'], tags:['BHC','Free','TB-DOTS'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b25', name:'Tondo I-A Health Center', address:'Juan Luna St, Tondo, Manila', district:'District I', lat:14.6130, lng:120.9660, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'Complete Blood Count (CBC)', 'OB-GYN'], tags:['BHC','Free','Konsulta'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b26', name:'Del Pan Health Center', address:'Del Pan, Tondo, Manila', district:'District II', lat:14.6200, lng:120.9710, type:'BHC', services: ['General Medicine', 'TB-DOTS Treatment', 'Vaccination / Immunization'], tags:['BHC','Free','TB-DOTS'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b27', name:'Gagalangin Health Center', address:'Gagalangin, Tondo, Manila', district:'District II', lat:14.6260, lng:120.9700, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'OB-GYN', 'Complete Blood Count (CBC)'], tags:['BHC','Free','Konsulta'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
  { id:'b28', name:'Santa Mesa Health Center', address:'Old Sta. Mesa, Manila', district:'District VI', lat:14.6000, lng:121.0050, type:'BHC', services: ['General Medicine', 'Vaccination / Immunization', 'TB-DOTS Treatment', 'Dental / Oral Health'], tags:['BHC','Free','TB-DOTS','Dental'], isBHC:true, isPhilHealthKonsulta:true, isPhilHealthAccredited:false, acceptsWalkIn:true, acceptsReferral:false, hasEmergency:false, inpatient:false, outpatient:true, hasLaboratory:false, hasDiagnostics:false, hasMalasakitCenter:false, hasSeniorLane:false, hours:'8:00 AM - 5:00 PM', is24Hours:false, typicalWaitLevel:'low', unverified: true },
]

// ── Haversine distance in km ──
export function haversineKm(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371
  const dLat = (lat2 - lat1) * Math.PI / 180
  const dLng = (lng2 - lng1) * Math.PI / 180
  const a = Math.sin(dLat/2)**2 + Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLng/2)**2
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a))
}
